# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /

# mysql
spring:
  jackson:
    time-zone: GMT+8
  # 环境 dev|test|prod
  profiles:
    active: dev